import bg from "../../Assets/Images/bgchat.jpg";

export const style = {
  container: {
    boxSizing: "border-box",
    bgcolor: "#EEEEEE",
    height: "100dvh",
    position: "relative",
  },
  bgBack: {
    width: "100%",
    height: "23dvh",
    bgcolor: "#009688",
    position: "absolute",
    top: 0,
    left: 0,
  },
  wrapper: {
    width: "97%",
    flexDirection: "row",
    boxShadow: "rgba(0, 0, 0, 0.24) 0px 3px 8px",
    position: "absolute",
    mx: "auto",
    left: 0,
    right: 0,
    mt: "2rem",
    height: "92%",
  },
  innerWrapperLeft: {
    flexGrow: 1,
    bgcolor: "#FFFF",
  },
  innerWrapperRight: {
    flexGrow: 8,
    bgcolor: "white",
    overflow: "hidden",
    position: "relative",
  },
  profileTabRight: {
    bgcolor: "#EEEEEE",
    borderLeft: "1px solid rgba(0,0,0,0.3)",
    px: "1rem",
    py: "0.7rem",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileTabLeft: {
    bgcolor: "#EEEEEE",
    px: "1rem",
    py: "0.7rem",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  profileList: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    px: "1rem",
    py: "0.7rem",
    borderBottom: "1px solid rgba(0,0,0,0.1)",
  },
  searchField: {
    width: "95%",
    "& .MuiInput-input::placeholder": {
      opacity: 0.7,
      fontSize: "0.8rem",
      textAlign: "center",
    },
    "& .MuiInputBase-root.Mui-focused:after": {
      borderBottom: "2px solid #1BD741",
    },
    "& .MuiInputBase-root.MuiInput-root:before": {
      borderBottom: "none",
    },
  },
  chatSpace: {
    width:"100%",
    position: "absolute",
    height: "-webkit-fill-available",
    backgroundImage: `url(${bg})`,
    overflow: "auto",
    px: "1rem",
    pt: "2rem",
    pb: "6rem",
  },
  status: {
    fontSize: "0.8rem",
    color: "#1BD660",
    textAlign: "start",
  },
  time: {
    fontSize: "0.8rem",
    color: "rgba(0,0,0,0.6)",
  },
  name: {
    textAlign: "start",
  },
  chatActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    bgcolor: "#EEEEEE",
    position: "absolute",
    bottom: 0,
    width: "100%",
    boxShadow: "rgba(149, 157, 165, 0.2) 0px 8px 24px",
    px: "1rem",
    py: "0.7rem",
    "& .MuiSvgIcon-root": {
      fontSize: "2rem",
    },
  },
  chatInput: {
    "&.MuiTextField-root": {
      width: "85%",
      bgcolor: "#FFF",
      borderRadius: 1,
      height: "42px",
      justifyContent: "end",
    },
    "& .MuiInputBase-root.MuiInput-root:before": {
      borderBottom: "none",
    },
    "& .MuiInputBase-root.Mui-focused:after": {
      borderBottom: "none",
    },
  },
  senderMsg: {
    color: "black",
    bgcolor: "#dcf8c6",
    px: "1rem",
    py: "0.5rem",
    borderRadius: 2,
    ml: "auto",
    my: "0.5rem",
  },
  receiverMsg: {
    color: "black",
    bgcolor: "#FFF",
    px: "1rem",
    py: "0.5rem",
    borderRadius: 2,
    my: "0.5rem",
  },
};
